# Generated by Django 5.0.1 on 2024-01-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
