# Generated by Django 5.0.1 on 2024-01-09 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_like_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
