# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background: url(/Users/asydoruk/Desktop/TestPy/img/back.jpeg)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.seachBox = QtWidgets.QLineEdit(self.centralwidget)
        self.seachBox.setFrame(False)
        self.seachBox.setPlaceholderText("Select City")
        self.seachBox.setGeometry(QtCore.QRect(150, 260, 321, 41))
        self.seachBox.setStyleSheet("background: rgb(93,177,217);\n"
                                    " color: #fff;\n"
                                    "border: 0px solid black\n")
        self.seachBox.setAlignment(QtCore.Qt.AlignCenter)
        self.seachBox.setObjectName("seachBox")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(490, 260, 121, 41))
        self.searchButton.setStyleSheet("  margin-right: 10px;\n"
                                        "  background: rgb(93,177,217);\n"
                                        "  color: #fff;\n"
                                        "  text-decoration: none;\n"
                                        "  font-size: 13px;\n"
                                        "  line-height: 38px;\n"
                                        "  border-radius: 50px;\n"
                                        "  width: 170px;\n"
                                        "  text-align: center;\n"
                                        "  border-radius: 10px;")
        self.searchButton.setObjectName("searchButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
