repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest revision
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest revision
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest revision
    hooks:
      - id: isort

